#!/bin/bash

word="$1"
file="$2"

if [ $$# -lt 2 ]; then
echo "Usage: jgrep WORD FILE"
exit 1
fi

if [ ! -f "$file" ]; then
echo "File doesn't exist: $file"
exit 1
fi

echo "==== Jaewoong's Grep ===="
echo "Word: $word"
echo "File: $file"
echo

echo "[Matching lines]"
grep -n -i "$word" "$file"

echo
echo "[Count]"
grep -i "$word" "$file" | wc -l
